### PR TITLE
honor 'false' as 'null' for nullable class typehints on domain constructor parameters

### PR DESCRIPTION
**Pull request by pmjones**

### CODE REVIEW

**Comment by ElGigi** [comment]
I'm blocked by old composer.json.
https://github.com/atlasphp/Atlas.Transit/pull/3

**Comment by pmjones** [comment]
Current master composer.json is https://github.com/atlasphp/Atlas.Transit/blob/0.x/composer.json -- did I fail to apply #3 correctly?

**Comment by ElGigi** [comment]
Yes it's fine applied on 0.X branch. But the issue branch don't contains this modification on composer.json.

**Comment by pmjones** [comment]
Gah! Fixed.

**Comment by ElGigi** [comment]
Ok 👍 
It's works fine! Thanks.

**Pull request merged**
